<?php $task = $this->content; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdn.jsdelivr.net/npm/@heroicons/outline@latest/css/heroicons.min.css" rel="stylesheet">
     
    <title>Task list</title>
</head>
<body class="bg-amber-100">
 
<div class="mx-auto mt-20 ">
<h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">these are all your tasks</h1>
<table class="mx-auto my-4 border-collapse border-4 border-blue-500 table-auto">
  <thead class="bg-blue-200 text-amber-600">
    <tr>
      <th class="p-4 text-center border-4 border-blue-500">User</th>
      <th class="p-4 text-center border-4 border-blue-500">Task</th>
      <th class="p-4 text-center border-4 border-blue-500">Status</th>
      <th class="p-4 text-center border-4 border-blue-500">Date Start</th>
      <th class="p-4 text-center border-4 border-blue-500">Date ending</th>
      <th class="p-4 text-center border-4 border-blue-500">View</th>
      <th class="p-4 text-center border-4 border-blue-500">Edit</th>
      <th class="p-4 text-center border-4 border-blue-500">Delete</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($task as $tasks):?>
      
      <tr>
        <td class="p-4 text-center border border-blue-500"><?php echo $tasks['user'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $tasks['task'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $tasks['status'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $tasks['start_date'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $tasks['end_date'];?></td>
        <td class="p-4 text-center border border-blue-500"><a href="view?id=<?php echo $tasks['id'] ?>"><svg svg class=" inline-block  w-6 h-6 align-middle" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="green" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" /></svg></a>
        </td>
        <td class="p-4 text-center border border-blue-500"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
        </svg>
        </td>
        <td class="p-4 text-center border border-blue-500 "><a href="#"><svg class=" inline-block  w-6 h-6 align-middle" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" /></svg></a>
        </td>
      </tr>
      <?php endforeach?>
  </tbody>
</table>
</div>
<div class="max-w-sm mx-auto text-center">
    <!-- <form  action="#" method="POST">
    <div class="flex justify-between p-2">
        <div class="w-1/2 px-4"> 
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full cursor-pointer">buscar</button>
        </div>
        <input type="search" name="search" class="bg-white focus:outline-none focus:shadow-outline border border-gray-300 rounded-lg py-2 px-4 block appearance-none leading-normal w-full" placeholder="Buscar tarea..." required>
    </div>
    </form> -->
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4 mt-6 cursor-pointer"><a href="addTask.phtml">Add new task</a> </button>
    </div>
  
 <footer class="fixed bottom-0 w-full">
  <nav class="bg-blue-500 p-2">
    <a href="/" class="text-white font-bold"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg></a>
  </nav>
 </footer>

</body>
</html>