<?php $task = $this->content; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdn.jsdelivr.net/npm/@heroicons/outline@latest/css/heroicons.min.css" rel="stylesheet">
     
    <title>View Task</title>
</head>
<body class="bg-amber-100">
 
<div class="mx-auto mt-20 ">
<h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">Here is your tasks</h1>
<table class="mx-auto my-4 border-collapse border-4 border-blue-500 table-auto">
  <thead class="bg-blue-200 text-amber-600">
    <tr>
      <th class="p-4 text-center border-4 border-blue-500">User</th>
      <th class="p-4 text-center border-4 border-blue-500">Task</th>
      <th class="p-4 text-center border-4 border-blue-500">Status</th>
      <th class="p-4 text-center border-4 border-blue-500">Date Start</th>
      <th class="p-4 text-center border-4 border-blue-500">Date ending</th>
      </tr>
  </thead>
  <tbody>
   
      <tr>
        <td class="p-4 text-center border border-blue-500"><?php echo $task['user'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $task['task'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $task['status'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $task['start_date'];?></td>
        <td class="p-4 text-center border border-blue-500"><?php echo $task['end_date'];?></td>
          </tr>
    </tbody>
</table>
</div>
 <footer class="fixed bottom-0 w-full">
  <nav class="bg-blue-500 p-2">
    <a href="taskList" class="text-white font-bold"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg></a>
  </nav>
 </footer>

</body>
</html>