<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com/?plugins=forms"></script>
    <title>Create</title>
</head>
<body>
     
     <div >
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <div class="w-full px-16 py-20 mt-6 overflow-hidden bg-white rounded-lg lg:max-w-4xl">
          

          <div class="w-full px-6 py-4 bg-white rounded shadow-md ring-1 ring-gray-900/10">

          <!-- FOOOOORM -->
            <form method="POST" action="">
              <!-- Task -->
              <div>
                <label class="block text-sm font-bold text-gray-700" for="task">
                  Task
                </label>

                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-right focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="text" name="task" placeholder="What to do" />
              </div>
              <!-- Status -->
              <div>
                <label class="block text-sm font-bold text-gray-700" for="status">
                  Status
                </label>
                <select name="status" class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                    <option value="pending" 
                        >Pending</option>
                    <option value="running"  
                        >Running</option>
                    <option value="finished"  
                        >Finished</option>
                </select>
                
              </div>
              <!-- Start -->
              <div>
                <label class="block text-sm font-bold text-gray-700" for="startDate">
                  Start
                </label>

                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-right focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="date" name="startDate" value="2023-07-22" min="2023-01-01" max="2023-12-31" />
              </div>
              <!-- Finish -->
              <div>
                <label class="block text-sm font-bold text-gray-700" for="endDate">
                  Finish
                </label>

                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-right focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="date" name="startDate" value="2023-07-22" min="2023-01-01" max="2023-12-31" />
              </div>

              
              <label for="start">Start date:</label>


              <div class="flex items-center justify-start mt-4 gap-x-2">
                <button type="submit"
                  class="inline-block text-sm px-4 py-2 leading-none bg-transparent hover:bg-teal-500 text-teal-500 font-semibold hover:text-white py-2 px-4 border border-teal-500 hover:border-transparent rounded ">
                  Save
                </button>
                 <a href= "./" class="inline-block text-sm px-4 py-2 leading-none bg-transparent hover:bg-teal-500 text-teal-500 font-semibold hover:text-white py-2 px-4 border border-teal-500 hover:border-transparent rounded">Cancel</a>
                
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</body>
</html>



