<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    
</head>
    <title>User Registration</title>
</head>
<body class="bg-amber-100">
    <div class="mx-auto max-w-2xl mt-20 ">
    <h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">User Registration</h1>
    <form action="user" method="post">
    <div class="max-w-sm mx-auto">
        <fieldset class= "border border-blue-700 p-8 text-center bg-blue-200">
        <div class="my-5">   
        <label for="username">Username
                <input type="text" id="username" name="inpUsername" required class="border border-black rounded-xl">
            </label>
        </div> 
        <div class="my-5">
            <label for="password">Password<input type="password" id="password" name="inpPassword" required class="border border-black rounded-xl bg-white" minlength="3"></label>
        </div>
        <div >            
             <input type="submit" value="create account" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded cursor-pointer">
        </div>
            
        </fieldset>
    </div>    
    
    </form>
    </div>
    <footer class="fixed bottom-0 w-full">
  <nav class="bg-blue-500 p-2">
    <a href="/" class="text-white font-bold"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg></a>
  </nav>
 </footer>
    
</body>
</html>