<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    
</head>
    <title>Home page</title>
</head>
<body class="bg-amber-100">
    <div class="mx-auto max-w-2xl mt-20 ">
    <h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">¡Welcome to task manager!</h1>
    <form action="user" method="post">
    <div class="max-w-sm mx-auto">
        <fieldset class= "border border-blue-700 p-8 text-center bg-blue-200">
        <div class="my-5">   
        <label for="username">Username
                <input type="text" id="username" name="inpUsername" required class="border border-black rounded-xl">
            </label>
        </div> 
        <div class="my-5">
            <label for="password">Password <input type="password" id="password" name="inpPassword" required class="border border-black rounded-xl bg-white" minlength="3"></label>
        </div>
        <div >            
            <input type="submit" value="login" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded mr-5 cursor-pointer">
            <input type="submit" value="create account" name="createAccount"class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded cursor-pointer">
        </div>
            
        </fieldset>
    </div>    
    
    </form>
    </div>
    
</body>
</html>